DROP TABLE IF EXISTS BillingProfile;
CREATE TABLE BillingProfile (
    id CHAR(36) NOT NULL PRIMARY KEY,
    userId CHAR(36) NOT NULL UNIQUE,
    type ENUM('INDIVIDUAL', 'COMPANY') NOT NULL DEFAULT 'INDIVIDUAL',
    fullName VARCHAR(191),
    companyName VARCHAR(191),
    taxNumber VARCHAR(191),
    country VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    postalCode VARCHAR(255) NOT NULL,
    street VARCHAR(255) NOT NULL,
    phone VARCHAR(191),
    createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);
